/*
 * @Author: hyl 2126419009@qq.com
 * @Date: 2023-12-04 11:34:52
 * @LastEditors: hyl 2126419009@qq.com
 * @LastEditTime: 2023-12-04 17:48:19
 * @FilePath: /chatgpt-app/app/layout.tsx
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
import AppContextProvider from '@/components/AppContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>{children}</AppContextProvider>
        </body>
    </html>
  )
}
